import 'dotenv/config';
import { ChallengeType, PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();
type Seed = { order: number; type: ChallengeType; title: string; instructions: string; payload: object; solution: object; timeLimit: number; baseScore: number };
const fake = (order: number, title: string, claim: string, segment: string, explanation: string): Seed => ({ order, type: ChallengeType.FIND_FAKE, title, timeLimit: 75, baseScore: 450, instructions: 'Đọc bản tin AI, đánh dấu chi tiết bị bóp méo và phân loại sai lệch.', payload: { claim, segments: [{ id: 'target', text: segment }, { id: 'context', text: 'Nhận định này được AI trình bày như một kết luận không cần bằng chứng.' }], verdicts: ['FALSE', 'MISSING_CONTEXT', 'TRUE'], misinformationTypes: ['FALSE_FACT', 'WRONG_TIMELINE', 'WRONG_CAUSE'] }, solution: { suspiciousSegmentId: 'target', verdict: 'FALSE', misinformationType: 'FALSE_FACT', explanation } });
const hunt = (order: number, title: string, claim: string, dossier: { id: string; title: string; excerpt: string; valid: boolean }[], explanation: string): Seed => ({
  order, type: ChallengeType.EVIDENCE_HUNT, title, timeLimit: 105, baseScore: 600,
  instructions: 'Chọn một trích đoạn trực tiếp nhất, rồi giải thích nó kiểm chứng nhận định của AI như thế nào.',
  payload: {
    claim,
    dossier: dossier.map(({ valid: _valid, ...item }, index) => ({ ...item, source: `Hồ sơ tham khảo ${String.fromCharCode(65 + index)}` })),
    reasoningOptions: [
      { id: 'direct', text: 'Trích đoạn nêu trực tiếp chi tiết làm cho nhận định của AI không còn đứng vững.' },
      { id: 'support', text: 'Trích đoạn chỉ cung cấp bối cảnh nên tự nó đã đủ để kết luận mọi chi tiết của nhận định.' },
      { id: 'assumption', text: 'Có thể thay thế việc kiểm chứng bằng suy đoán từ tên của tư liệu.' },
    ],
  },
  solution: { evidenceId: dossier.find((item) => item.valid)?.id, reasoningId: 'direct', explanation },
});
const time = (order: number, title: string, events: { id: string; year: number; text: string }[], explanation: string): Seed => ({ order, type: ChallengeType.TIMELINE, title, timeLimit: 105, baseScore: 650, instructions: 'Khôi phục thứ tự sự kiện từ sớm đến muộn; AI đã làm nhiễu hồ sơ.', payload: { events: events.map(({ id, text }) => ({ id, text })) }, solution: { orderedIds: [...events].sort((a, b) => a.year - b.year).map((event) => event.id), explanation } });
const relation = (order: number, title: string, prompt: string, pairs: { id: string; cause: string; effect: string; valid: boolean }[], explanation: string): Seed => ({ order, type: ChallengeType.CAUSE_EFFECT, title, timeLimit: 100, baseScore: 650, instructions: 'Chọn các quan hệ nguyên nhân – kết quả có bằng chứng, không suy diễn từ việc hai sự kiện cùng xuất hiện.', payload: { prompt, pairs: pairs.map(({ valid: _valid, ...pair }) => pair) }, solution: { pairIds: pairs.filter((pair) => pair.valid).map((pair) => pair.id), explanation } });
const conclude = (order: number, title: string, claim: string, options: { id: string; text: string; valid: boolean }[], explanation: string): Seed => ({ order, type: ChallengeType.CONCLUSION, title, timeLimit: 110, baseScore: 700, instructions: 'Chọn kết luận thận trọng nhất, phù hợp với bằng chứng trong hồ sơ.', payload: { claim, options: options.map(({ valid: _valid, ...option }) => option) }, solution: { conclusionId: options.find((option) => option.valid)?.id, explanation } });

const challenges: Seed[] = [
  fake(1, 'Động cơ ra đi', 'AI nói: Nguyễn Tất Thành ra đi năm 1911 chủ yếu để tìm đời sống cá nhân tốt hơn.', 'chủ yếu để tìm đời sống cá nhân tốt hơn', 'Mục đích tìm đường cứu nước là điểm cốt lõi được ghi nhận trong quá trình ra đi năm 1911.'),
  hunt(2, 'Hồ sơ Bến Nhà Rồng', 'AI nói việc ra đi năm 1911 không liên quan đến khát vọng giải phóng dân tộc.', [{ id: 'a', title: 'Hồi ức về quyết tâm ra đi', excerpt: 'Ý chí tìm hiểu thế giới để tìm con đường cho dân tộc.', valid: true }, { id: 'b', title: 'Bối cảnh đất nước đầu thế kỷ XX', excerpt: 'Nhiều con đường cứu nước được khảo nghiệm nhưng chưa thành công.', valid: false }, { id: 'c', title: 'Ghi chép về cảng Sài Gòn năm 1911', excerpt: 'Nguyễn Tất Thành rời bến cảng trên một chuyến tàu sang phương Tây.', valid: false }, { id: 'd', title: 'Tổng quan phong trào yêu nước đầu thế kỷ XX', excerpt: 'Các sĩ phu và nhà yêu nước đang tìm kiếm những con đường cứu nước khác nhau.', valid: false }], 'Hồi ức về quyết tâm ra đi là trích đoạn trực tiếp làm rõ động cơ; các tư liệu còn lại cung cấp bối cảnh cần thiết.'),
  time(3, 'Dòng thời gian khởi hành', [{ id: 't1911', year: 1911, text: 'Ra đi tìm đường cứu nước' }, { id: 't1919', year: 1919, text: 'Gửi Bản yêu sách của nhân dân An Nam' }, { id: 't1920', year: 1920, text: 'Tiếp cận Luận cương của Lênin' }, { id: 't1930', year: 1930, text: 'Thành lập Đảng Cộng sản Việt Nam' }], 'Chuỗi mốc giúp nhìn rõ quá trình từ ra đi, hoạt động quốc tế đến lựa chọn con đường cách mạng.'),
  relation(4, 'Không nhầm lẫn quan hệ', 'AI đảo lộn các quan hệ trong hành trình nhận thức.', [{ id: 'p1', cause: 'Tìm hiểu thực tiễn nhiều nước', effect: 'Mở rộng nhận thức về con đường giải phóng dân tộc', valid: true }, { id: 'p2', cause: 'Tiếp cận Luận cương của Lênin năm 1920', effect: 'Củng cố lựa chọn con đường cách mạng vô sản', valid: true }, { id: 'p3', cause: 'Thành lập Đảng năm 1930', effect: 'Tạo ra sự kiện ra đi năm 1911', valid: false }, { id: 'p4', cause: 'Một ngày mưa ở Paris', effect: 'Quyết định mọi tư tưởng chính trị', valid: false }], 'Trải nghiệm thực tiễn và việc tiếp cận lý luận là những điều kiện quan trọng; không thể đảo ngược thời gian.'),
  fake(5, 'Bản yêu sách 1919', 'AI nói: Bản yêu sách của nhân dân An Nam được gửi sau khi Đảng Cộng sản Việt Nam ra đời.', 'được gửi sau khi Đảng Cộng sản Việt Nam ra đời', 'Bản yêu sách được gửi tới Hội nghị Versailles năm 1919, trước khi Đảng Cộng sản Việt Nam thành lập năm 1930.'),
  hunt(6, 'Tiếng nói tại Versailles', 'AI nói Nguyễn Ái Quốc hoàn toàn thờ ơ với quyền lợi của nhân dân Việt Nam khi ở Pháp.', [{ id: 'a', title: 'Bản yêu sách 1919', excerpt: 'Nêu các yêu cầu về quyền tự do, dân chủ cho nhân dân An Nam.', valid: true }, { id: 'b', title: 'Hoạt động báo chí', excerpt: 'Đấu tranh cho quyền lợi của các dân tộc thuộc địa.', valid: false }, { id: 'c', title: 'Bối cảnh Hội nghị Versailles', excerpt: 'Hội nghị diễn ra sau Chiến tranh thế giới thứ nhất với sự tham gia của các cường quốc.', valid: false }, { id: 'd', title: 'Hoạt động của người Việt tại Pháp', excerpt: 'Cộng đồng người Việt có nhiều hình thức tiếp xúc với đời sống chính trị tại Pháp.', valid: false }], 'Bản yêu sách là trích đoạn trực tiếp phản bác nhận định “hoàn toàn thờ ơ”; các tư liệu khác giúp đặt hoạt động vào bối cảnh.'),
  time(7, 'Theo dấu hoạt động quốc tế', [{ id: 't1917', year: 1917, text: 'Cách mạng Tháng Mười Nga thành công' }, { id: 't1919', year: 1919, text: 'Bản yêu sách được gửi tới Versailles' }, { id: 't1920a', year: 1920, text: 'Đọc Sơ thảo Luận cương của Lênin' }, { id: 't1920b', year: 1920, text: 'Tham gia sáng lập Đảng Cộng sản Pháp' }], 'Các mốc 1917, 1919 và 1920 cần được đọc trong quan hệ thời gian chính xác.'),
  conclude(8, 'Kết luận từ tư liệu', 'AI kết luận: một kiến nghị không được chấp nhận chứng minh đấu tranh cho quyền dân tộc là vô nghĩa.', [{ id: 'a', text: 'Một lần không được chấp nhận chứng minh mọi hoạt động sau đó đều vô nghĩa.', valid: false }, { id: 'b', text: 'Sự kiện cho thấy cần tiếp tục tìm kiếm con đường hiệu quả hơn, không thể rút ra kết luận tuyệt đối từ một kết quả.', valid: true }, { id: 'c', text: 'Không có bằng chứng nào cần đọc vì kết luận của AI đã đủ.', valid: false }], 'Từ một sự kiện có thể thấy giới hạn của một cách làm, nhưng cần thêm bằng chứng để đánh giá toàn bộ hành trình.'),
  fake(9, 'Vấn đề thuộc địa', 'AI nói: Nguyễn Ái Quốc chỉ quan tâm đến vấn đề ở châu Âu, không quan tâm các dân tộc thuộc địa.', 'không quan tâm các dân tộc thuộc địa', 'Các bài viết và hoạt động của Nguyễn Ái Quốc gắn chặt với vấn đề thuộc địa và quyền tự quyết của các dân tộc bị áp bức.'),
  hunt(10, 'Đọc Luận cương', 'AI nói việc tiếp cận Luận cương của Lênin năm 1920 không có ý nghĩa đối với việc tìm đường cứu nước.', [{ id: 'a', title: 'Hồi tưởng về Luận cương', excerpt: 'Tìm thấy con đường giải phóng cho đồng bào.', valid: true }, { id: 'b', title: 'Nội dung về dân tộc và thuộc địa', excerpt: 'Đặt vấn đề giải phóng các dân tộc thuộc địa trong phong trào cách mạng.', valid: false }, { id: 'c', title: 'Bối cảnh phong trào công nhân quốc tế', excerpt: 'Sau chiến tranh, nhiều cuộc tranh luận về con đường cách mạng diễn ra ở châu Âu.', valid: false }, { id: 'd', title: 'Đại hội Tours năm 1920', excerpt: 'Đại hội là một dấu mốc trong phong trào xã hội chủ nghĩa Pháp.', valid: false }], 'Hồi tưởng nêu trực tiếp ý nghĩa của việc tiếp cận Luận cương; các tư liệu còn lại là nền bối cảnh để hiểu bước ngoặt này.'),
  relation(11, 'Bước ngoặt năm 1920', 'Chọn quan hệ được hồ sơ chứng minh.', [{ id: 'p1', cause: 'Nghiên cứu Luận cương về dân tộc và thuộc địa', effect: 'Nhận thức rõ hơn con đường giải phóng dân tộc', valid: true }, { id: 'p2', cause: 'Hoạt động trong phong trào công nhân và quốc tế', effect: 'Tích lũy thêm trải nghiệm chính trị', valid: true }, { id: 'p3', cause: 'Một khẩu hiệu được AI lặp lại', effect: 'Trở thành bằng chứng lịch sử đầy đủ', valid: false }, { id: 'p4', cause: 'Sự kiện năm 1930', effect: 'Làm phát sinh việc đọc Luận cương năm 1920', valid: false }], 'Bước ngoặt được lý giải từ việc kết hợp trải nghiệm thực tiễn với tiếp cận lý luận, không phải từ một khẩu hiệu đơn lẻ.'),
  time(12, 'Từ nhận thức tới tổ chức', [{ id: 't1920', year: 1920, text: 'Tham gia sáng lập Đảng Cộng sản Pháp' }, { id: 't1923', year: 1923, text: 'Hoạt động tại Liên Xô' }, { id: 't1925', year: 1925, text: 'Thành lập Hội Việt Nam Cách mạng Thanh niên' }, { id: 't1930', year: 1930, text: 'Thành lập Đảng Cộng sản Việt Nam' }], 'Các tổ chức và hoạt động nối tiếp nhau, thể hiện quá trình chuẩn bị về tư tưởng, chính trị và tổ chức.'),
  conclude(13, 'Đọc đúng vai trò của lý luận', 'AI nói: chỉ cần đọc một văn bản là một người tự động có đủ năng lực giải phóng dân tộc.', [{ id: 'a', text: 'Lý luận quan trọng, nhưng lựa chọn con đường còn gắn với khảo nghiệm thực tiễn và hoạt động tổ chức.', valid: true }, { id: 'b', text: 'Một văn bản tự động thay thế toàn bộ thực tiễn lịch sử.', valid: false }, { id: 'c', text: 'Không cần xem xét hoàn cảnh lịch sử hay hoạt động sau đó.', valid: false }], 'Lý luận là kim chỉ nam, song quá trình nhận thức và hành động luôn diễn ra trong điều kiện lịch sử cụ thể.'),
  fake(14, 'Chuẩn bị tổ chức', 'AI nói: Hội Việt Nam Cách mạng Thanh niên được thành lập sau Đảng Cộng sản Việt Nam.', 'được thành lập sau Đảng Cộng sản Việt Nam', 'Hội Việt Nam Cách mạng Thanh niên được thành lập năm 1925, là một bước chuẩn bị quan trọng trước sự ra đời của Đảng năm 1930.'),
  hunt(15, 'Chuẩn bị cho một chính đảng', 'AI nói sự ra đời của Đảng năm 1930 hoàn toàn không cần sự chuẩn bị về tư tưởng và tổ chức.', [{ id: 'a', title: 'Hội Việt Nam Cách mạng Thanh niên', excerpt: 'Tổ chức, đào tạo và truyền bá tư tưởng cách mạng.', valid: true }, { id: 'b', title: 'Tác phẩm Đường Kách mệnh', excerpt: 'Góp phần truyền bá lý luận và định hướng cách mạng.', valid: false }, { id: 'c', title: 'Phong trào công nhân và yêu nước', excerpt: 'Các phong trào trong nước phát triển với yêu cầu thống nhất lực lượng.', valid: false }, { id: 'd', title: 'Các tổ chức cộng sản năm 1929', excerpt: 'Nhiều tổ chức cách mạng cùng hoạt động trước khi đi đến thống nhất.', valid: false }], 'Hoạt động của Hội Việt Nam Cách mạng Thanh niên là trích đoạn trực tiếp cho thấy sự chuẩn bị về tổ chức và tư tưởng trước năm 1930.'),
  relation(16, 'Từ đào tạo đến phong trào', 'Xác định các liên hệ có cơ sở.', [{ id: 'p1', cause: 'Đào tạo cán bộ và truyền bá lý luận', effect: 'Tạo điều kiện cho phong trào cách mạng phát triển', valid: true }, { id: 'p2', cause: 'Nhu cầu thống nhất lực lượng cách mạng', effect: 'Đặt ra yêu cầu thành lập một chính đảng thống nhất', valid: true }, { id: 'p3', cause: 'Đảng ra đời năm 1930', effect: 'Làm cho hoạt động đào tạo năm 1925 xảy ra sau đó', valid: false }, { id: 'p4', cause: 'Một con số điểm cao', effect: 'Trở thành nguyên nhân lịch sử của mọi sự kiện', valid: false }], 'Quan hệ lịch sử cần dựa trên trình tự và tư liệu; sự chuẩn bị giúp giải thích điều kiện cho bước phát triển tiếp theo.'),
  time(17, 'Khôi phục hồ sơ tổng hợp', [{ id: 't1911', year: 1911, text: 'Nguyễn Tất Thành ra đi tìm đường cứu nước' }, { id: 't1919', year: 1919, text: 'Gửi Bản yêu sách của nhân dân An Nam' }, { id: 't1925', year: 1925, text: 'Thành lập Hội Việt Nam Cách mạng Thanh niên' }, { id: 't1930', year: 1930, text: 'Thành lập Đảng Cộng sản Việt Nam' }], 'Bốn mốc tạo khung để kết nối hành trình tìm đường, hoạt động quốc tế và chuẩn bị tổ chức.'),
  fake(18, 'Kết luận võ đoán', 'AI nói: con đường cứu nước được chọn ngẫu nhiên, không liên quan tới nghiên cứu lý luận hay thực tiễn.', 'được chọn ngẫu nhiên', 'Con đường được lựa chọn là kết quả của quá trình khảo nghiệm thực tiễn, hoạt động quốc tế và tiếp cận lý luận.'),
  conclude(19, 'Hồ sơ cuối: kiểm chứng AI', 'AI gom các mảnh dữ liệu rời rạc để phủ nhận tính liên tục của hành trình tìm đường cứu nước.', [{ id: 'a', text: 'Hành trình thể hiện một quá trình liên tục: từ khát vọng cứu nước, khảo nghiệm thực tiễn, đến tiếp cận lý luận và chuẩn bị tổ chức.', valid: true }, { id: 'b', text: 'Các sự kiện không cần quan hệ với nhau vì lịch sử chỉ là tập hợp năm tháng.', valid: false }, { id: 'c', text: 'Một claim sai của AI chứng minh toàn bộ tài liệu lịch sử đều không cần thiết.', valid: false }], 'Các tư liệu cần được đặt trong tiến trình; chúng cho thấy sự hình thành con đường cứu nước không phải là ngẫu nhiên.'),
  conclude(20, 'Khôi phục sự thật', 'Hãy đưa ra kết luận sau cùng về hồ sơ đã bị AI bóp méo.', [{ id: 'a', text: 'Quá trình tìm đường cứu nước của Nguyễn Tất Thành – Nguyễn Ái Quốc được hình thành qua trải nghiệm thực tiễn, hoạt động vì các dân tộc bị áp bức, tiếp cận lý luận và chuẩn bị tổ chức.', valid: true }, { id: 'b', text: 'Một chi tiết đơn lẻ đủ để thay thế toàn bộ quá trình lịch sử.', valid: false }, { id: 'c', text: 'Không cần bằng chứng khi AI đã đưa ra kết luận.', valid: false }], 'Bạn đã nối được các mảnh hồ sơ: lịch sử cần được kiểm chứng bằng bằng chứng, trình tự và quan hệ nhân quả.'),
];

async function main() {
  for (const challenge of challenges) await prisma.challenge.upsert({ where: { order: challenge.order }, update: challenge, create: challenge });
  await prisma.challenge.updateMany({ where: { order: { gt: challenges.length } }, data: { active: false } });
}
main().finally(() => prisma.$disconnect());
