ALTER TYPE "ChallengeType" ADD VALUE IF NOT EXISTS 'CAUSE_EFFECT';
ALTER TYPE "ChallengeType" ADD VALUE IF NOT EXISTS 'CONCLUSION';

ALTER TABLE "PlayerSession"
  ADD COLUMN IF NOT EXISTS "currentOrder" INTEGER NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS "correctCount" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "criteriaHit" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "criteriaTotal" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "combo" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "bestCombo" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "totalSeconds" INTEGER NOT NULL DEFAULT 0;

ALTER TABLE "ChallengeAttempt"
  ADD COLUMN IF NOT EXISTS "criteriaHit" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "criteriaTotal" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "elapsedSeconds" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "comboBonus" INTEGER NOT NULL DEFAULT 0;
